theme: 
title: Y. Wang Lab @ Cornell
email: yuhanwang@cornell.edu
description: >- # this means to ignore newlines until "baseurl:"
  Y. Wang Lab @ Cornell
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://ywanglab.me" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: None
github_username: wangyuhan01

# Build settings
theme: minima
plugins:
  - jekyll-feed

sass:
  style: compressed

# Custom CSS
custom_css: /assets/css/custom.css
